language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: VqaIvmlpddN83tlpYxvu5MdbmECYMBYLCRUhr0058sLtAi7QYW01h/arDhxOcePH249mMJjT/b3kscFC10fIu+B4Pnlq88L0cHf7qVuS/Bi+3oh8wU5OAHLON/UUrQAdJeWfEMQlJWtWZr+AEjPSKRCIBU07MYHOMxoLBScngqeLrmQaUOrvTLD+cc+uMsOuN0MQ6SN2XnGAuw6VNisH0UvXqEJY1Si433hsghoGntNHJ1u15/NSe6AtfygWe/VCPAJY4l6PdXfcdbgSNEu/G+z10yfe+KSnt6EuC9r3reIAEu+4wPXBU/rC5gG2oBfd9rO61C8UQgE9d5LBOsW5tzCKoWQJ0Zx17rV/FknF7mkau8AynSTw8Nn9bMYrRwbf+zrXCaC29eIvEpnhSIaLEuFLiSxhTtyMmx9I9ZbHayXKTcFERrchHbmC0lF/9+3kab2aJwTdBHxkRGIEN+E3Qhi5RUssNoZcLA5wUHzJAoFSaYIhetUwe82KRStXTqf/Gyq6HtTbkVb7S24IEOjSX0W4loBNChNwemPQRZrGsmIcstSOG+j3dQNdkRnXDtqQnkDj4zp8xxPQMzgd4q2zrjGf9GFru4C0HecDW0BaRl15M3FnzySbMvgwvg6wU1ekidIEg3948k56+xitO0AVcSIsvlOjZVo1rpuqhdEzQxY=
  app: inimini
  on:
    repo: elingerojo/inimini
