language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  api_key:
    secure: Q6zJkweVzda39ZdiuMifYZJY/0hk6Wxhw509zVjlPQogCa72eGeJezc/hDolZdtgRlpghUnMkoC+Jqv0s9hG2p7ASb+KiYArz8bASoGesxnLBlZQcmL1HdbfLCOvYQh8KV85Ldr+GGSGFMRIQE12qn78OzeG5x2+En7d7JRU5qzh1k5XAaNbhE3YaGWV0iVSZwLnHTvhgFlvBlcg8/3G9EGYvIFsacdtjnbWUbFrw8hl8iPPgk7j0oOR283UDUjc9xEIjGRXYCXKOxwz+zO2yDGPuLk5I8D/yXZOJwPWzP8jUdoTvWu03h2VLhsWVDqeEKn7eJ4YGP+SCHlkiyHhwxCEBJ4HnuMrMyIq/4yrOMbVqzPgXTrY19JILq2c4QDQB6DpLaf/HDDE0wdAMTgM8lzFqumpf9XHE/Vjvp8U6vws4euE9AIAYUghmflpchtBAiT4Ec5elX5yllbBruxQyW+89oVKLdfplhl75rfLEg90jYuFQVK0g/BeLSVp98ufgzTmJzGQyQMfd040ZuyRUmwcpx6tzMwt2OyRr5z5J2me2+5Px/huWD7HTB7fwgdjAgasMzsxoW7KbHtBLWlImtOvQpFlYjtXC3MSVCeCm1a6AK3H7VPQpXZzExTOu5+xMJknAS0tKKA17H2eadHfrqyxWcAkzCBz+zeOv/Zu3oU=
