language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  api_key:
    secure: "AvgxPODeW/7jr2RcHf12MqG5ZNOU2WRgAWBoQT46+lbxQ4xAAsOcyMdQGfkAR9l4cZqnQgbygoA97msyb8V87dcn7RrkeQfqnCyPdD2vOzHSEMQT03tCrCIxNBlET7XxCc6w2n6FBmx8mjU1IDi/T1Fc4NFSCgjCL+HQOsNFcC3bXKz12di7mT0zeE33/q5e7P9WtRHBTvBiWwjnKdUi516BH19mTiE2Nb9QOq9uc5+nc4Gh1zwpZTwcUC+fSB0PBG+JiZhSyvSUPL4Dt1SbASsXcmnzEZ6RWa4sHkbPjTiEecgGAugLziAdVXs1kc3V+hd5fJoy0x05su6IXb27EOlhND10nfZjiirpKH/RN9sHo35cffcbgShkMtEVyLs24n/4cBZ9S4XscTJievS1aadKk//mSIKV3fREvhmHDsbN9btASQ/KO6/FejkvLibgfwKhcZEU6qNAe7ZRPIkQkFY1ob/nlv3L/6Yb/gFTi2sV5TpIAYnfUa5C+qH3TDWdCMTr4ql7JvoAp3WLfI3BI7KR6LJ5A2Z76tvYOWEiozrvTwj6xEq0KSmgS1sYFgO+ko+Sy2r1R5D89LcSyKgVSmHkHbPhIDHp2h3f+uWJbJ73E0wp+hEiCH0bKQkrRFbuY6C2XCNvgNw86VK7SJ9ufg4Ln2W74/N9/MIYJPc71MY="
