language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  api_key:
    secure: p+xtP/6FOln3DO5shhJ2qRyszPD6b5+WVaEcKD7igrxFp6Qn62a0y9yUSsAnrhc81+ELzpO4KhwagVzySOrSUtIMm9LkxpiZz7JCIWho6dX5oYPstqF/Pa4sh8MWTYArFX8oY9fCC+eSUCZ+7n57flb1DfcdTJs6o1K4c8I/jxvlwG/eZmMEEB/SzbO97GNGpZG1LUjLX6JMsSZEWCwb2/bEb5WyTYceixK6qCY4Qd6RatjByR9YLXB+TaTw+idVZcTVwQ3dFKUqNPrdWAzQwvbEZipaEB0EYlTvseDjtsBcczlMbWrwUkRynK9zKzZJSjJOOoYldxbL0Tb1DZ7EVE4Y1rgfrwewN0Y45h0qce0Ym/hBZfoOKC1RHPqjxG47e8X/CWLHj9Or6eSimL62ScmJwz9o3X0Q7OpVMCWi/mEG9jlUCrc31n5+dR8YqIez4XgtvBI2QnXvap9VTaWhZanNSSeG8r6ai9YdpTikkshq8Qg0LgxqSMI+b42nxF0p2wf/G3SWnzM5xxYQIyJlMtg3fuVjJ/SYKXClgwgQy/Y6j9wlrEExEusVjt5Sl4vj6ZW5IXIk2BlCQS/HSovPuJubALbykq67uM5j/EHGPEDnn3630qliyWs/rfOWVwM7NHoJTUZNx6JHJy+0QsmZqiCyijMmSR3wh9E5/gp2JTE=
