# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 22:00
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'length less than two')])),
                ('category', models.CharField(choices=[('LL', 'League of Legends'), ('OW', 'Overwatch')], max_length=2)),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(2, 'length less than two')])),
                ('price', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1, 'minimum allowable $1'), django.core.validators.MaxValueValidator(500, 'more than max allowable price')])),
                ('photo', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('boughttimes', models.IntegerField(default=0)),
                ('sellmsg', models.TextField(blank=True, default='Please provide link to VOD', max_length=1000)),
                ('avgstars', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayname', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('avatar', models.CharField(max_length=500)),
                ('about', models.TextField(blank=True, max_length=2000, null=True)),
                ('slogan', models.CharField(blank=True, max_length=500, null=True)),
                ('vanitymail', models.CharField(default='replace.me@roast.gg', max_length=128)),
                ('emailoptin', models.BooleanField(default=True)),
                ('emailverified', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
